create table if not exists public.books (
  id bigint generated by default as identity primary key,
  title text not null,
  author text not null,
  category text not null default 'General',
  cover_image_url text not null default '',
  created_at timestamptz not null default now()
);

alter table public.books
  add column if not exists category text not null default 'General';

alter table public.books
  add column if not exists cover_image_url text not null default '';

alter table public.books
  add column if not exists created_at timestamptz not null default now();

alter table public.books enable row level security;
